### ISSUE TITLE
Windows install issue for javascript package

### ISSUE THREAD

**Issue by Bilal-S** [opentimestamps/javascript-opentimestamps#34]
Receive the following error when running `npm install` on project that is including this package. Install version 0.4.3 of opentimestamps:

```
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Base\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by RCasatta** [comment]
not sure why, that looks a python error

**Comment by lvaccaro** [comment]
It is related to `node-gyp` package: it looks like this version of `node-gyp` require python2. 
Anyway `node-gyp` is not a required anymore because `keccak` was removed.
